package enumsemjava;


public enum Carro {
    //NOMES NA CLASSE ENUM SEMPRE EM MAIUSCULO POIS SÃO STATIC FINAL OU SEJA SÓ SÃO UTILIZADOS UMA VEZ E SEPARADOS POR VIRGULA
    GOLF,
    VECTRA,
    FUSCA,
    STRADA
}
